"""add relationship role columns

Revision ID: 598d3db2b20d
Revises: 1854eb4589b1
Create Date: 2026-07-06 19:32:36.022209

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '598d3db2b20d'
down_revision: str | None = '1854eb4589b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_a', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('role_b', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_column('role_b')
        batch_op.drop_column('role_a')

    # ### end Alembic commands ###
